name: Alexandre Duarte
favicon: null
layout_spectrum: 0.99917
typography_spectrum: 0.5432993369176984
title: The World According to Me Myself and I
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070606'
    - '#b0b0b0'
    - '#676767'
    - '#3a3b3b'
  brandStrength: 0.5534589292947203
  lightness: 0.8807037170045078
  saturation: 0.020508148008957505
  rhythmicContrast: 0.9981585973873734
purpose: []
